"""Tests for the compactor. Pinned by ``agent-development/04-learn-compaction/tests.md``.

``LLMClient`` is mocked via :mod:`pytest_mock`; the compactor never hits the
network.
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from typing import TYPE_CHECKING

import pytest

from simple_cli_coder_with_rag.application.compactor import (
    CompactionError,
    Compactor,
)
from simple_cli_coder_with_rag.domain.compacted import CompactedSession
from simple_cli_coder_with_rag.domain.messages import (
    AssistantMessage,
    UserMessage,
)

if TYPE_CHECKING:
    from pytest_mock import MockerFixture


def _valid_json() -> str:
    """Return a JSON string that round-trips into a ``CompactedSession``.

    ``session_id`` and ``created_at`` are placeholders — the compactor
    overrides them with the values passed in / freshly computed.
    """
    return (
        '{"session_id": "llm-supplied",'
        ' "created_at": "2026-10-01T00:00:00Z",'
        ' "summary": "ok",'
        ' "errors": [],'
        ' "decisions": []}'
    )


def test_compactor_uses_compactor_model_setting(mocker: MockerFixture) -> None:
    """The ``model`` kwarg forwarded to ``complete`` matches the constructor arg."""
    fake_llm = mocker.MagicMock()
    fake_llm.complete.return_value = _valid_json()

    compactor = Compactor(llm=fake_llm, compactor_model="compactor-model-x")
    compactor.compact("sid", [UserMessage(content="hi")])

    assert fake_llm.complete.call_args.kwargs["model"] == "compactor-model-x"


def test_compactor_passes_messages_to_llm(mocker: MockerFixture) -> None:
    """Every input ``Message`` reaches ``LLMClient.complete`` (transcript appears in the prompt)."""
    fake_llm = mocker.MagicMock()
    fake_llm.complete.return_value = _valid_json()

    compactor = Compactor(llm=fake_llm, compactor_model="m")
    messages_in = [UserMessage(content="hi"), AssistantMessage(content="hello")]
    compactor.compact("sid", messages_in)

    sent = fake_llm.complete.call_args.args[0]
    # The compactor embeds the transcript as a JSON-serialised line per role
    # (e.g. ``USER: {"role":"user","content":"hi"}``) so a substring check is
    # the right invariant — the exact wrapper class is implementation detail.
    sent_text = "\n".join(m.content for m in sent)
    assert "USER" in sent_text
    assert '"content":"hi"' in sent_text
    assert "ASSISTANT" in sent_text
    assert '"content":"hello"' in sent_text


def test_compactor_validates_json_response(mocker: MockerFixture) -> None:
    """Valid JSON is parsed into a ``CompactedSession`` with the right fields."""
    fake_llm = mocker.MagicMock()
    fake_llm.complete.return_value = _valid_json()

    compactor = Compactor(llm=fake_llm, compactor_model="m")
    result = compactor.compact("sid", [UserMessage(content="hi")])

    assert isinstance(result, CompactedSession)
    assert result.summary == "ok"
    assert result.errors == []
    assert result.decisions == []


def test_compactor_rejects_invalid_json(mocker: MockerFixture) -> None:
    """Non-JSON replies raise the project-owned ``CompactionError``."""
    fake_llm = mocker.MagicMock()
    fake_llm.complete.return_value = "not json"

    compactor = Compactor(llm=fake_llm, compactor_model="m")

    with pytest.raises(CompactionError):
        compactor.compact("sid", [UserMessage(content="hi")])


def test_compactor_rejects_invalid_record(mocker: MockerFixture) -> None:
    """JSON with an item that violates schema (occurrences < 1) raises ``CompactionError``."""
    fake_llm = mocker.MagicMock()
    fake_llm.complete.return_value = (
        '{"session_id": "x",'
        ' "created_at": "2026-10-01T00:00:00Z",'
        ' "summary": "ok",'
        ' "errors": [{"signature": "x", "message": "m", "occurrences": 0}],'
        ' "decisions": []}'
    )

    compactor = Compactor(llm=fake_llm, compactor_model="m")

    with pytest.raises(CompactionError):
        compactor.compact("sid", [UserMessage(content="hi")])


def test_compactor_uses_session_id_and_now(mocker: MockerFixture) -> None:
    """The result's ``session_id`` is the input; ``created_at`` is recent."""
    fake_llm = mocker.MagicMock()
    fake_llm.complete.return_value = _valid_json()

    before = datetime.now(UTC)
    compactor = Compactor(llm=fake_llm, compactor_model="m")
    result = compactor.compact("my-sid", [UserMessage(content="hi")])
    after = datetime.now(UTC)

    assert result.session_id == "my-sid"
    # Allow generous slack for CI clock jitter but assert the timestamp was
    # generated by the compactor itself (not echoed from the LLM).
    assert before - timedelta(seconds=5) <= result.created_at <= after + timedelta(seconds=5)


def test_compactor_short_circuits_on_empty_messages(mocker: MockerFixture) -> None:
    """``compact([], ...)`` returns ``(empty session)`` without calling the LLM."""
    fake_llm = mocker.MagicMock()

    compactor = Compactor(llm=fake_llm, compactor_model="m")
    result = compactor.compact("sid", [])

    fake_llm.complete.assert_not_called()
    assert result.summary == "(empty session)"
    assert result.errors == []
    assert result.decisions == []
    assert result.session_id == "sid"
