"""``coder`` entry point.

Responsibilities:

* parse ``--version`` / ``--help`` / ``--reset`` via :mod:`argparse`;
* on ``--reset``, wipe the local data directory **before** any logger or
  REPL state is touched (so a destructive run never races a live SQLite
  handle);
* otherwise, configure loguru to write to ``platformdirs.user_log_dir``,
  load :class:`Settings`, build the ``LLMClient`` for the active
  provider, build the session store + compactor + ``KnowledgeService``
  facade, generate a fresh UUIDv4 session id, and start the
  :class:`~simple_cli_coder_with_rag.presentation.repl.Repl`.
"""

from __future__ import annotations

import argparse
import sys

from simple_cli_coder_with_rag import __version__
from simple_cli_coder_with_rag.application.compactor import Compactor
from simple_cli_coder_with_rag.application.knowledge_service import (
    KnowledgeService,
    build_chunker,
)
from simple_cli_coder_with_rag.application.session_store import SessionStore
from simple_cli_coder_with_rag.infrastructure.llm import build_llm_client
from simple_cli_coder_with_rag.infrastructure.local_paths import LocalPaths
from simple_cli_coder_with_rag.infrastructure.logging import configure_logging
from simple_cli_coder_with_rag.infrastructure.settings import Settings
from simple_cli_coder_with_rag.presentation.commands import AppState
from simple_cli_coder_with_rag.presentation.commands.clear import ClearCommand
from simple_cli_coder_with_rag.presentation.commands.exit import ExitCommand
from simple_cli_coder_with_rag.presentation.commands.help import HelpCommand
from simple_cli_coder_with_rag.presentation.commands.learn import LearnCommand
from simple_cli_coder_with_rag.presentation.commands.version import VersionCommand
from simple_cli_coder_with_rag.presentation.registry import CommandRegistry
from simple_cli_coder_with_rag.presentation.repl import Repl


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="coder",
        description="Interactive coding assistant with optional RAG context.",
    )
    parser.add_argument("--version", action="store_true", help="print the package version and exit")
    parser.add_argument(
        "--reset",
        action="store_true",
        help="wipe the local data directory after a y/N prompt",
    )
    return parser


def _build_registry() -> CommandRegistry:
    registry = CommandRegistry()
    registry.register(HelpCommand(registry))
    registry.register(ExitCommand())
    registry.register(ClearCommand())
    registry.register(VersionCommand())
    registry.register(LearnCommand())
    return registry


def main(argv: list[str] | None = None) -> int:
    """Entry point. Returns a shell exit code."""
    parser = _build_parser()
    args = parser.parse_args(argv)

    if args.reset:
        # Short-circuit: destructive path must not touch the logger or the
        # REPL, so it cannot race with a live SQLite connection.
        return _reset_local_data()

    if args.version:
        print(__version__)
        return 0

    configure_logging()

    _settings, app_state = _bootstrap_app_state()
    if app_state is None:
        # Settings validation failed; the helper already wrote the message
        # to stderr. We deliberately do **not** start the REPL here — the
        # prompt would corrupt the message.
        return 2

    registry = _build_registry()
    repl = Repl(registry=registry, app_state=app_state)
    repl.run()
    return 0


def _bootstrap_app_state() -> tuple[Settings | None, AppState | None]:
    """Instantiate Settings, build the active LLM client, and bundle into AppState.

    Returns ``(None, None)`` if the active provider's API key is missing —
    in that case the helper prints a friendly message to stderr (the only
    place we write to stderr before ``prompt_toolkit`` takes over) and the
    caller exits with code 2.
    """
    try:
        settings = Settings()
    except RuntimeError as exc:
        # Active provider's key is missing. This is the only stderr write
        # before the REPL takes over.
        print(f"coder: {exc}", file=sys.stderr)
        return None, None

    llm_client = build_llm_client(settings)
    chat_model = _resolve_chat_model(settings)
    compactor_model = _resolve_compactor_model(settings)

    # Session store and compactor are wired *before* the KnowledgeService so
    # the service receives both in its constructor. The session id is
    # generated by the store (UUIDv4 hex) so the REPL has a stable,
    # filesystem-friendly identifier to pass to ``/learn`` and to use as a
    # filename prefix on disk.
    session_store = SessionStore(root=LocalPaths.data_dir() / "sessions")
    session_id = session_store.current_id()
    compactor = Compactor(llm=llm_client, compactor_model=compactor_model)
    chunker = build_chunker(settings.chunker_strategy)

    knowledge = KnowledgeService(
        llm=llm_client,
        chat_model=chat_model,
        session_store=session_store,
        compactor=compactor,
        chunker=chunker,
    )
    app_state = AppState(
        version=__version__,
        llm=llm_client,
        knowledge=knowledge,
        session_id=session_id,
        session_store=session_store,
        chunker=chunker,
    )
    return settings, app_state


def _resolve_chat_model(settings: Settings) -> str:
    """Return the model name to pass to ``LLMClient.complete`` for chat turns.

    ``settings.chat_model`` is the explicit override (set via the
    ``CHAT_MODEL`` env var). An empty string means "no override"; in that
    case we fall back to the active provider's per-provider default so the
    REPL still has a usable model out of the box.
    """
    if settings.chat_model:
        return settings.chat_model
    return getattr(settings, f"{settings.default_provider}_model")


def _resolve_compactor_model(settings: Settings) -> str:
    """Return the model name to pass to ``LLMClient.complete`` from the compactor.

    Mirrors :func:`_resolve_chat_model` but reads
    :attr:`Settings.compactor_model` instead — empty string falls back to
    the active provider's per-provider default so a user who never sets
    ``COMPACTOR_MODEL`` still gets a working compaction pipeline.
    """
    if settings.compactor_model:
        return settings.compactor_model
    return getattr(settings, f"{settings.default_provider}_model")


def _reset_local_data() -> int:
    """Wipe local data files after an interactive y/N prompt.

    Returns 0 whether the user confirms or aborts, and on an empty data
    directory. The REPL and the loguru file sink are intentionally not
    created here.
    """
    targets = LocalPaths.reset_targets()
    data_dir = LocalPaths.data_dir()
    print(f"This will delete {len(targets)} file(s) under {data_dir}:")
    for path in targets:
        print(f"  {path}")
    print("Continue? [y/N] ", end="", flush=True)
    answer = sys.stdin.readline().strip()
    if answer != "y":
        print("Aborted.")
        return 0
    for path in targets:
        path.unlink(missing_ok=True)
    print("Reset complete.")
    return 0


if __name__ == "__main__":  # pragma: no cover - script entry only
    raise SystemExit(main())
